### ISSUE TITLE
Add Support for EOS

### ISSUE THREAD

**Issue by ryanmerolle** [supertylerc/network-static-analysis#14]
For an example of how to add this support, see #3, which adds Junos support.

**Comment by supertylerc** [comment]
Thanks for submitting this issue!  I'll look into this on Monday when I have access to some EOS configuration snippets.  Should be quick and easy as a first pass.

**Comment by ryanmerolle** [comment]
May I do it myself?  I will probably raise a PR to update some documentation for new users as well.

**Comment by supertylerc** [comment]
Sure!  Contributions always welcome :)
